### ISSUE TITLE
Separate private and public API 

### ISSUE THREAD

**Issue by Levi-Lesches** [micazi/darted_cli#1]
Nice package! The API docs are kind of cluttered because they're showing every single file and folder, because everything is directly in lib 

What you should do instead: 
- move everything into lib/src
- decide which classes/functions you want people to be able to import
- out of those, make groups, like IO and args
- in lib/, make individual "header files" that just look like this:

```dart
// lib/args.dart
export "src/args/parser.dart";
export "src/helpers/arg_tree.dart";
// More arg-related exports here
```

This way, you split your package into smaller libraries, that each get their own page in the API docs, and that people can import individually, like this

```dart
import "package:darted_cli/args.dart";
```

This also follows the [standard pub convention](https://dart.dev/tools/pub/package-layout#public-directories)

**Comment by micazi** [comment]
Thank you so much, @Levi-Lesches, For the feedback!
I do realize I blazed through the development of the package because i needed it for implementation in one of my projects, and neglected a lot of standards. 
I will get back and handle everything once i get the time to, hopefully really soon.
Thank you so much once more for taking the time to share your thoughts and help make the package better, I truly appreciate it.

**Comment by micazi** [comment]
Updated in the 0.1.3 release.
Thanks once more for your feedback.
